apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: 183631308419.dkr.ecr.us-east-1.amazonaws.com/emailservice:2
        ports:
        - containerPort: 80

